import type { Lesson, TalkLine } from "./types";
import {
  bi,
  buildWord,
  copy,
  guess,
  hear,
  kanaWord,
  kanjiMeet,
  lesson,
  opt,
  pattern,
  scene,
  useIt,
} from "./helpers";

const U4 = bi("Out in the town", "শহরে বাইরে");
const U5 = bi("Asking the world", "পৃথিবীকে জিজ্ঞেস");
const U6 = bi("School days", "স্কুলের দিন");
const U7 = bi("Living the day", "দিন যাপন");

function you(
  promptEn: string,
  promptBn: string,
  options: { ja: string; romaji: string; en: string; bn: string; correct: boolean }[],
): TalkLine {
  return {
    role: "you",
    prompt: bi(promptEn, promptBn),
    options: options.map((o) => ({
      ja: o.ja,
      romaji: o.romaji,
      meaning: bi(o.en, o.bn),
      correct: o.correct,
    })),
  };
}

export const lessonsB: Lesson[] = [
  lesson(
    "coming-home",
    "town",
    U4,
    11,
    "return",
    bi("Coming home", "বাড়ি ফেরা"),
    bi("The day folds. You walk back through the same door.", "দিন গুটিয়ে আসে। একই দরজা দিয়ে ফিরে আসেন।"),
    [
      scene("return", "Dusk. A familiar door. A light already on inside.", "গোধূলি। চেনা দরজা। ভেতরে আলো জ্বলে আছে।"),
      hear("うちに かえります。", "uchi ni kaerimasu", "I go home.", "আমি বাড়ি ফিরি।"),
      hear("いま かえります。", "ima kaerimasu", "I'm going home now.", "এখনই বাড়ি ফিরছি।"),
      hear("きょうは つかれました。", "kyou wa tsukaremashita", "Today I got tired.", "আজ ক্লান্ত হয়েছি।"),
      copy("ただいま。", "tadaima", "I'm home.", "আমি এসেছি।"),
      hear("おかえりなさい。", "okaerinasai", "Welcome home.", "ফিরে এসে ভালো।"),
      pattern(
        [
          ["いきます", "ikimasu", "go (away from here)", "যাওয়া (এখান থেকে)"],
          ["きます", "kimasu", "come (toward here)", "আসা (এখান দিকে)"],
          ["かえります", "kaerimasu", "return home", "বাড়ি ফেরা"],
        ],
        "Japanese cares which way the body is facing. かえります is not just 'go' — it is the path back to where you live.",
        "জাপানি ভাষা শরীর কোনদিকে মুখ করে আছে তা খেয়াল রাখে। かえります শুধু 'যাওয়া' নয় — যেখানে আপনি থাকেন সেখানে ফেরার পথ।",
      ),
      useIt("You open the door. People are already inside.", "দরজা খুললেন। ভিতরে মানুষ আছে।", [
        { ja: "ただいま。", romaji: "tadaima", en: "I'm home.", bn: "আমি এসেছি।", correct: true },
        { ja: "いってきます。", romaji: "ittekimasu", en: "I'm heading out.", bn: "আমি বেরোচ্ছি।", correct: false },
        { ja: "こんにちは。", romaji: "konnichiwa", en: "Hello.", bn: "হ্যালো।", correct: false },
      ]),
      kanjiMeet("くる", "来", "くる", "あした 来ます。", "ashita kimasu", "I will come tomorrow.", "আগামীকাল আসব।"),
      {
        kind: "talk",
        lines: [
          {
            role: "them",
            ja: "もう かえりますか。",
            romaji: "mou kaerimasu ka",
            meaning: bi("Are you going home already?", "এত তাড়াতাড়ি বাড়ি ফিরছেন?"),
          },
          you("Yes — you are heading home.", "হ্যাঁ — বাড়ি ফিরছেন।", [
            {
              ja: "はい、 かえります。",
              romaji: "hai, kaerimasu",
              en: "Yes, I'm going home.",
              bn: "হ্যাঁ, বাড়ি ফিরছি।",
              correct: true,
            },
            {
              ja: "いいえ、 みずです。",
              romaji: "iie, mizu desu",
              en: "No, it's water.",
              bn: "না, এটি পানি।",
              correct: false,
            },
          ]),
        ],
      },
    ],
  ),

  lesson(
    "shopping",
    "town",
    U4,
    12,
    "shop",
    bi("Shopping", "কেনাকাটা"),
    bi("A small shop. You point, you ask, you receive.", "ছোট দোকান। ইঙ্গিত, প্রশ্ন, গ্রহণ।"),
    [
      scene("shop", "Shelves, a counter, a paper bag. Someone waits, not rushing.", "তাক, কাউন্টার, কাগজের ব্যাগ। কেউ অপেক্ষা করছে, তাড়াহুড়ো নেই।"),
      hear("すみません。", "sumimasen", "Excuse me.", "মাফ করবেন।"),
      hear("これを ください。", "kore o kudasai", "This one, please.", "এটি দিন, অনুগ্রহ করে।"),
      hear("いくらですか。", "ikura desu ka", "How much is it?", "এটি কত?"),
      hear("ひゃくえんです。", "hyaku en desu", "It's 100 yen.", "১০০ ইয়েন।"),
      hear("ありがとう ございます。", "arigatou gozaimasu", "Thank you.", "ধন্যবাদ।"),
      pattern(
        [
          ["これを ください。", "kore o kudasai", "This, please.", "এটি দিন।"],
          ["みずを ください。", "mizu o kudasai", "Water, please.", "পানি দিন।"],
          ["パンを ください。", "pan o kudasai", "Bread, please.", "রুটি দিন।"],
        ],
        "ください is a hand held out. か at the end of いくらですか turns it into a question. You already heard か when someone asked なんですか.",
        "ください হলো এগিয়ে দেওয়া হাত। いくらですか-এর শেষে か একে প্রশ্ন করে। なんですか-তে か আগেই শুনেছেন।",
      ),
      useIt("You want that item on the counter.", "কাউন্টারের সেই জিনিসটি চান।", [
        {
          ja: "これを ください。",
          romaji: "kore o kudasai",
          en: "This, please.",
          bn: "এটি দিন।",
          correct: true,
        },
        { ja: "おはよう。", romaji: "ohayou", en: "Good morning.", bn: "সুপ্রভাত।", correct: false },
        {
          ja: "おやすみなさい。",
          romaji: "oyasuminasai",
          en: "Good night.",
          bn: "শুভ রাত্রি।",
          correct: false,
        },
      ]),
      kanaWord("ください", "please give me", "দয়া করে দিন", [
        { char: "く", romaji: "ku" },
        { char: "だ", romaji: "da" },
        { char: "さ", romaji: "sa" },
        { char: "い", romaji: "i" },
      ]),
      {
        kind: "talk",
        lines: [
          { role: "them", ja: "いらっしゃいませ。", romaji: "irasshaimase", meaning: bi("Welcome (to the shop).", "স্বাগতম (দোকানে)।") },
          you("You want this, and you need the price.", "এটি চান, দামও জানতে চান।", [
            {
              ja: "これを ください。 いくらですか。",
              romaji: "kore o kudasai. ikura desu ka",
              en: "This, please. How much?",
              bn: "এটি দিন। কত?",
              correct: true,
            },
            {
              ja: "わたしは ねこです。",
              romaji: "watashi wa neko desu",
              en: "I am a cat.",
              bn: "আমি একটি বিড়াল।",
              correct: false,
            },
          ]),
          {
            role: "them",
            ja: "さんびゃくえんです。",
            romaji: "sanbyaku en desu",
            meaning: bi("300 yen.", "৩০০ ইয়েন।"),
          },
          you("Receive it kindly.", "কৃতজ্ঞভাবে নিন।", [
            {
              ja: "ありがとう ございます。",
              romaji: "arigatou gozaimasu",
              en: "Thank you.",
              bn: "ধন্যবাদ।",
              correct: true,
            },
            { ja: "さようなら。", romaji: "sayounara", en: "Goodbye.", bn: "বিদায়।", correct: false },
          ]),
        ],
      },
    ],
  ),

  lesson(
    "simple-questions",
    "asking",
    U5,
    13,
    "ask",
    bi("Asking simple questions", "সহজ প্রশ্ন"),
    bi("What, who, where — three doors you can open.", "কী, কে, কোথায় — তিনটি দরজা।"),
    [
      scene("ask", "A street corner. Someone looks around, then asks.", "রাস্তার মোড়। কেউ চারদিকে দেখে, তারপর জিজ্ঞেস করে।"),
      hear("それは なんですか。", "sore wa nan desu ka", "What is that?", "ওটি কী?"),
      hear("だれですか。", "dare desu ka", "Who is it?", "কে?"),
      hear("どこですか。", "doko desu ka", "Where is it?", "কোথায়?"),
      hear("いつ いきますか。", "itsu ikimasu ka", "When will you go?", "কখন যাবেন?"),
      hear("はい。", "hai", "Yes.", "হ্যাঁ।"),
      hear("いいえ。", "iie", "No.", "না।"),
      pattern(
        [
          ["なん / なに", "nan / nani", "what", "কী"],
          ["だれ", "dare", "who", "কে"],
          ["どこ", "doko", "where", "কোথায়"],
          ["いつ", "itsu", "when", "কখন"],
        ],
        "A Japanese question often keeps the same sentence and only adds か. Listen: どこです。 then どこですか。 The rise lives at the end.",
        "জাপানি প্রশ্ন প্রায়ই একই বাক্য রাখে, শুধু か যোগ করে। শুনুন: どこです। তারপর どこですか। উঠে যাওয়া শেষে থাকে।",
      ),
      useIt("You don't know what that thing is.", "ওই জিনিসটি কী জানেন না।", [
        {
          ja: "それは なんですか。",
          romaji: "sore wa nan desu ka",
          en: "What is that?",
          bn: "ওটি কী?",
          correct: true,
        },
        {
          ja: "それは ねこです。",
          romaji: "sore wa neko desu",
          en: "That is a cat.",
          bn: "ওটি একটি বিড়াল।",
          correct: false,
        },
        { ja: "おはよう。", romaji: "ohayou", en: "Good morning.", bn: "সুপ্রভাত।", correct: false },
      ]),
      guess(
        "どこですか。",
        "doko desu ka",
        "Where is it?",
        "কোথায়?",
        "This question is looking for…",
        "এই প্রশ্ন খুঁজছে…",
        [
          opt("", "A place.", "একটি জায়গা।", true),
          opt("", "A time of day.", "দিনের একটি সময়।", false),
          opt("", "A person's name.", "কারও নাম।", false),
        ],
      ),
      {
        kind: "talk",
        lines: [
          {
            role: "them",
            ja: "がっこうは どこですか。",
            romaji: "gakkou wa doko desu ka",
            meaning: bi("Where is the school?", "স্কুল কোথায়?"),
          },
          you("Point over there.", "ওদিকে ইঙ্গিত করুন।", [
            {
              ja: "あそこです。",
              romaji: "asoko desu",
              en: "Over there.",
              bn: "ওদিকে।",
              correct: true,
            },
            {
              ja: "おいしいです。",
              romaji: "oishii desu",
              en: "It's delicious.",
              bn: "সুস্বাদু।",
              correct: false,
            },
          ]),
        ],
      },
    ],
  ),

  lesson(
    "what-time",
    "asking",
    U5,
    14,
    "time",
    bi("What time is it", "এখন কটা বাজে"),
    bi("Time is a sound you hear in stations and kitchens.", "সময় স্টেশন ও রান্নাঘরে শোনা একটি শব্দ।"),
    [
      scene("time", "A round clock on a kitchen wall. Morning light on the numbers.", "রান্নাঘরের দেয়ালে ঘড়ি। সংখ্যার উপর সকালের আলো।"),
      hear("いま なんじですか。", "ima nanji desu ka", "What time is it now?", "এখন কটা বাজে?"),
      hear("いちじです。", "ichiji desu", "It's one o'clock.", "একটা বাজে।"),
      hear("さんじです。", "sanji desu", "It's three o'clock.", "তিনটা বাজে।"),
      hear("じゅうじです。", "juuji desu", "It's ten o'clock.", "দশটা বাজে।"),
      hear("はん です。", "han desu", "It's half past.", "সাড়ে।"),
      hear("くじはん です。", "kuji han desu", "It's 9:30.", "সাড়ে নয়টা।"),
      pattern(
        [
          ["いちじ", "ichiji", "1 o'clock", "১টা"],
          ["にじ", "niji", "2 o'clock", "২টা"],
          ["さんじ", "sanji", "3 o'clock", "৩টা"],
          ["よじ", "yoji", "4 o'clock", "৪টা"],
          ["ごじ", "goji", "5 o'clock", "৫টা"],
          ["ろくじ", "rokuji", "6 o'clock", "৬টা"],
          ["しちじ", "shichiji", "7 o'clock", "৭টা"],
          ["はちじ", "hachiji", "8 o'clock", "৮টা"],
          ["くじ", "kuji", "9 o'clock", "৯টা"],
          ["じゅうじ", "juuji", "10 o'clock", "১০টা"],
          ["じゅういちじ", "juuichiji", "11 o'clock", "১১টা"],
          ["じゅうにじ", "juuniji", "12 o'clock", "১২টা"],
        ],
        "じ rides after the number and turns it into o'clock. はん is the half. You do not need to chant them — you will meet them on clocks.",
        "じ সংখ্যার পরে বসে তাকে ঘড়ির সময় করে। はん হলো অর্ধেক। মুখস্থ তালিকা নয় — ঘড়িতে এদের সাথে দেখা হবে।",
      ),
      useIt("Someone asks the time. The clock says 3.", "কেউ সময় জিজ্ঞেস করল। ঘড়িতে ৩।", [
        { ja: "さんじです。", romaji: "sanji desu", en: "It's 3 o'clock.", bn: "তিনটা বাজে।", correct: true },
        { ja: "みずです。", romaji: "mizu desu", en: "It's water.", bn: "এটি পানি।", correct: false },
        { ja: "はい。", romaji: "hai", en: "Yes.", bn: "হ্যাঁ।", correct: false },
      ]),
      kanjiMeet("じ", "時", "じ", "いま 何時ですか。", "ima nanji desu ka", "What time is it now?", "এখন কটা বাজে?"),
      {
        kind: "talk",
        lines: [
          {
            role: "them",
            ja: "いま なんじですか。",
            romaji: "ima nanji desu ka",
            meaning: bi("What time is it?", "এখন কটা বাজে?"),
          },
          you("It is 7 o'clock.", "এখন ৭টা।", [
            { ja: "しちじです。", romaji: "shichiji desu", en: "It's 7.", bn: "৭টা।", correct: true },
            { ja: "ねこです。", romaji: "neko desu", en: "It's a cat.", bn: "বিড়াল।", correct: false },
          ]),
        ],
      },
    ],
  ),

  lesson(
    "counting-life",
    "asking",
    U5,
    15,
    "numbers",
    bi("Numbers in life", "জীবনের সংখ্যা"),
    bi("Count things you can hold, not a naked list.", "হাতে ধরা যায় এমন জিনিস গণনা করুন, খালি তালিকা নয়।"),
    [
      scene("numbers", "Apples on a plate. Coins on a counter. Fingers unfolding.", "থালায় আপেল। কাউন্টারে মুদ্রা। আঙুল খুলছে।"),
      hear("ひとつ ください。", "hitotsu kudasai", "One, please. (of this thing)", "একটি দিন।"),
      hear("ふたつ ください。", "futatsu kudasai", "Two, please.", "দুটি দিন।"),
      hear("みっつ ください。", "mittsu kudasai", "Three, please.", "তিনটি দিন।"),
      hear("いち、 に、 さん。", "ichi, ni, san", "One, two, three.", "এক, দুই, তিন।"),
      hear("これ にこ です。", "kore niko desu", "These are two small things. (you'll hear こ later)", "এগুলো দুটি ছোট জিনিস।"),
      pattern(
        [
          ["いち", "ichi", "1", "১"],
          ["に", "ni", "2", "২"],
          ["さん", "san", "3", "৩"],
          ["よん / し", "yon / shi", "4", "৪"],
          ["ご", "go", "5", "৫"],
          ["ろく", "roku", "6", "৬"],
          ["なな / しち", "nana / shichi", "7", "৭"],
          ["はち", "hachi", "8", "৮"],
          ["きゅう / く", "kyuu / ku", "9", "৯"],
          ["じゅう", "juu", "10", "১০"],
        ],
        "ひとつ ふたつ みっつ is how you ask for pieces of something. いち に さん is the backbone you will hear in prices and time. Both live in shops, not in a chart.",
        "ひとつ ふたつ みっつ দিয়ে টুকরো চাওয়া হয়। いち に さん দাম ও সময়ের মেরুদণ্ড। দুটোই দোকানে বাঁচে, চার্টে নয়।",
      ),
      useIt("You want two of those apples.", "সেই আপেল দুটি চান।", [
        {
          ja: "ふたつ ください。",
          romaji: "futatsu kudasai",
          en: "Two, please.",
          bn: "দুটি দিন।",
          correct: true,
        },
        {
          ja: "おやすみなさい。",
          romaji: "oyasuminasai",
          en: "Good night.",
          bn: "শুভ রাত্রি।",
          correct: false,
        },
        {
          ja: "わたしは がくせいです。",
          romaji: "watashi wa gakusei desu",
          en: "I am a student.",
          bn: "আমি শিক্ষার্থী।",
          correct: false,
        },
      ]),
      kanjiMeet("いち", "一", "いち", "一つ ください。", "hitotsu kudasai", "One, please.", "একটি দিন।"),
      kanjiMeet("に", "二", "に", "二つ ください。", "futatsu kudasai", "Two, please.", "দুটি দিন।"),
      kanjiMeet("さん", "三", "さん", "三つ ください。", "mittsu kudasai", "Three, please.", "তিনটি দিন।"),
    ],
  ),

  lesson(
    "at-school",
    "school",
    U6,
    16,
    "school",
    bi("At school", "স্কুলে"),
    bi("A classroom is full of names you already almost know.", "শ্রেণিকক্ষে এমন নাম যেগুলো আপনি প্রায় চেনেন।"),
    [
      scene("school", "Desks in rows. A board. Morning light on paper.", "সারিতে ডেস্ক। একটি বোর্ড। কাগজে সকালের আলো।"),
      hear("ここは がっこうです。", "koko wa gakkou desu", "This is a school.", "এটি একটি স্কুল।", "ここは 学校です。"),
      hear("あの ひとは せんせいです。", "ano hito wa sensei desu", "That person is a teacher.", "ঐ ব্যক্তি একজন শিক্ষক।"),
      hear("わたしは がくせいです。", "watashi wa gakusei desu", "I am a student.", "আমি একজন শিক্ষার্থী।"),
      hear("にほんごを べんきょうします。", "nihongo o benkyou shimasu", "I study Japanese.", "আমি জাপানি পড়ি।"),
      hear("わかりました。", "wakarimashita", "I understood.", "বুঝেছি।"),
      hear("もう いちど おねがいします。", "mou ichido onegaishimasu", "Once more, please.", "আরেকবার, অনুগ্রহ করে।"),
      pattern(
        [
          ["せんせい", "sensei", "teacher", "শিক্ষক"],
          ["がくせい", "gakusei", "student", "শিক্ষার্থী"],
          ["がっこう", "gakkou", "school", "স্কুল"],
          ["べんきょうします", "benkyou shimasu", "study", "পড়াশোনা করা"],
        ],
        "わかりました is the feeling of a window opening. If it did not open, もう いちど — one more time — is a complete, kind sentence.",
        "わかりました হলো জানালা খোলার অনুভূতি। না খুললে もう いちど — আরেকবার — একটি পূর্ণ, সদয় বাক্য।",
      ),
      useIt("You did not catch the sentence.", "বাক্যটি ধরতে পারেননি।", [
        {
          ja: "もう いちど おねがいします。",
          romaji: "mou ichido onegaishimasu",
          en: "Once more, please.",
          bn: "আরেকবার।",
          correct: true,
        },
        { ja: "さようなら。", romaji: "sayounara", en: "Goodbye.", bn: "বিদায়।", correct: false },
        { ja: "おいしいです。", romaji: "oishii desu", en: "Delicious.", bn: "সুস্বাদু।", correct: false },
      ]),
      kanjiMeet("がっこう", "学校", "がっこう", "学校に 行きます。", "gakkou ni ikimasu", "I go to school.", "আমি স্কুলে যাই।"),
      kanjiMeet("せんせい", "先生", "せんせい", "先生は あそこです。", "sensei wa asoko desu", "The teacher is over there.", "শিক্ষক ওদিকে।"),
      {
        kind: "talk",
        lines: [
          {
            role: "them",
            ja: "わかりましたか。",
            romaji: "wakarimashita ka",
            meaning: bi("Did you understand?", "বুঝতে পেরেছেন?"),
          },
          you("You understood.", "বুঝেছেন।", [
            { ja: "はい、 わかりました。", romaji: "hai, wakarimashita", en: "Yes, I understood.", bn: "হ্যাঁ, বুঝেছি।", correct: true },
            { ja: "これは みずです。", romaji: "kore wa mizu desu", en: "This is water.", bn: "এটি পানি।", correct: false },
          ]),
        ],
      },
    ],
  ),

  lesson(
    "daily-moves",
    "school",
    U6,
    17,
    "daily",
    bi("Daily moves", "দৈনন্দিন চলা"),
    bi("A day is a chain of small verbs you already felt.", "একটি দিন ছোট ক্রিয়ার শৃঙ্খল যা আপনি আগেই অনুভব করেছেন।"),
    [
      scene("daily", "Sunrise, a bag, a desk, a lamp at night.", "সূর্যোদয়, একটি ব্যাগ, একটি ডেস্ক, রাতে বাতি।"),
      hear("ろくじに おきます。", "rokuji ni okimasu", "I get up at 6.", "৬টায় উঠি।"),
      hear("あさごはんを たべます。", "asagohan o tabemasu", "I eat breakfast.", "সকালের খাবার খাই।"),
      hear("はなします。", "hanashimasu", "I speak / I talk.", "আমি কথা বলি।"),
      hear("みます。", "mimasu", "I watch / I look.", "আমি দেখি।"),
      hear("よみます。", "yomimasu", "I read.", "আমি পড়ি।"),
      hear("かきます。", "kakimasu", "I write.", "আমি লিখি।"),
      hear("じゅういちじに ねます。", "juuichiji ni nemasu", "I go to bed at 11.", "১১টায় ঘুমাতে যাই।"),
      pattern(
        [
          ["おきます", "okimasu", "wake up / get up", "ঘুম থেকে ওঠা"],
          ["たべます", "tabemasu", "eat", "খাওয়া"],
          ["いきます", "ikimasu", "go", "যাওয়া"],
          ["はなします", "hanashimasu", "speak", "কথা বলা"],
          ["ねます", "nemasu", "sleep", "ঘুমানো"],
        ],
        "に after a time (ろくじに) is when the action happens — the same に that pointed at school. One little sound, two jobs you can feel from context.",
        "সময়ের পরে に (ろくじに) বলে কাজ কখন হয় — যে に স্কুলের দিকেও ইঙ্গিত করেছিল। একটি ছোট শব্দ, দুটি কাজ, পরিস্থিতি থেকে বোঝা যায়।",
      ),
      useIt("Night. You are going to sleep.", "রাত। ঘুমাতে যাচ্ছেন।", [
        { ja: "ねます。", romaji: "nemasu", en: "I go to sleep.", bn: "ঘুমাতে যাই।", correct: true },
        { ja: "おきます。", romaji: "okimasu", en: "I get up.", bn: "উঠি।", correct: false },
        { ja: "いきます。", romaji: "ikimasu", en: "I go.", bn: "যাই।", correct: false },
      ]),
      kanaWord("ねます", "sleep", "ঘুমানো", [
        { char: "ね", romaji: "ne" },
        { char: "ま", romaji: "ma" },
        { char: "す", romaji: "su" },
      ]),
      kanjiMeet("みる", "見", "みる", "テレビを 見ます。", "terebi o mimasu", "I watch TV.", "আমি টিভি দেখি।"),
    ],
  ),

  lesson(
    "days-of-week",
    "living",
    U7,
    18,
    "week",
    bi("Days of the week", "সপ্তাহের দিন"),
    bi("The week turns like weather. Names return every seven suns.", "সপ্তাহ আবহাওয়ার মতো ঘোরে। সাত সূর্যে নাম ফিরে আসে।"),
    [
      scene("week", "A paper calendar on the wall. Someone circles tomorrow.", "দেয়ালে কাগজের ক্যালেন্ডার। কেউ আগামীকালকে ঘিরে রাখে।"),
      hear("きょうは げつようびです。", "kyou wa getsuyoubi desu", "Today is Monday.", "আজ সোমবার।", "今日は 月曜日です。"),
      hear("あしたは かようびです。", "ashita wa kayoubi desu", "Tomorrow is Tuesday.", "আগামীকাল মঙ্গলবার।"),
      hear("きのうは にちようびでした。", "kinou wa nichiyoubi deshita", "Yesterday was Sunday.", "গতকাল রবিবার ছিল।"),
      pattern(
        [
          ["げつようび", "getsuyoubi", "Monday", "সোমবার"],
          ["かようび", "kayoubi", "Tuesday", "মঙ্গলবার"],
          ["すいようび", "suiyoubi", "Wednesday", "বুধবার"],
          ["もくようび", "mokuyoubi", "Thursday", "বৃহস্পতিবার"],
          ["きんようび", "kinyoubi desu", "Friday", "শুক্রবার"],
          ["どようび", "doyoubi", "Saturday", "শনিবার"],
          ["にちようび", "nichiyoubi", "Sunday", "রবিবার"],
        ],
        "ようび is the 'day-of-week' ending. きょう today, あした tomorrow, きのう yesterday. You will keep meeting them, not drilling them.",
        "ようび সপ্তাহের দিনের শেষাংশ। きょう আজ, あした আগামীকাল, きのう গতকাল। মুখস্থ নয়, বারবার দেখা।",
      ),
      useIt("Someone asks about today. It is Friday.", "কেউ আজকের কথা জিজ্ঞেস করল। শুক্রবার।", [
        {
          ja: "きんようびです。",
          romaji: "kinyoubi desu",
          en: "It's Friday.",
          bn: "শুক্রবার।",
          correct: true,
        },
        { ja: "みずです。", romaji: "mizu desu", en: "It's water.", bn: "পানি।", correct: false },
        { ja: "おはよう。", romaji: "ohayou", en: "Good morning.", bn: "সুপ্রভাত।", correct: false },
      ]),
      kanjiMeet("きょう", "今日", "きょう", "今日は 月曜日です。", "kyou wa getsuyoubi desu", "Today is Monday.", "আজ সোমবার।"),
      kanjiMeet("げつ", "月", "げつ / つき", "月曜日です。", "getsuyoubi desu", "It's Monday.", "সোমবার।"),
      kanjiMeet("ひ", "日", "ひ / にち", "日曜日です。", "nichiyoubi desu", "It's Sunday.", "রবিবার।"),
    ],
  ),

  lesson(
    "food-talk",
    "living",
    U7,
    19,
    "food",
    bi("Talking about food", "খাবার নিয়ে কথা"),
    bi("A small restaurant. Menus, steam, a simple want.", "ছোট রেস্তোরাঁ। মেনু, ভাপ, একটি সহজ চাওয়া।"),
    [
      scene("food", "A wooden counter, bowls, a handwritten menu.", "কাঠের কাউন্টার, বাটি, হাতে লেখা মেনু।"),
      hear("メニューを ください。", "menyu o kudasai", "The menu, please.", "মেনু দিন।"),
      hear("おすすめは なんですか。", "osusume wa nan desu ka", "What do you recommend?", "কী সুপারিশ করবেন?"),
      hear("ラーメンを ください。", "raamen o kudasai", "Ramen, please.", "রামেন দিন।"),
      hear("おいしいです。", "oishii desu", "It's delicious.", "সুস্বাদু।"),
      hear("ちょっと からいです。", "chotto karai desu", "It's a little spicy.", "একটু ঝাল।"),
      hear("おみずを ください。", "omizu o kudasai", "Water, please.", "পানি দিন।"),
      hear("おかいけい おねがいします。", "okaikei onegaishimasu", "The bill, please.", "বিল দিন।"),
      useIt("The food is good. Say so.", "খাবার ভালো। তাই বলুন।", [
        { ja: "おいしいです。", romaji: "oishii desu", en: "It's delicious.", bn: "সুস্বাদু।", correct: true },
        { ja: "つかれました。", romaji: "tsukaremashita", en: "I'm tired.", bn: "ক্লান্ত।", correct: false },
        { ja: "がっこうです。", romaji: "gakkou desu", en: "It's school.", bn: "স্কুল।", correct: false },
      ]),
      {
        kind: "talk",
        lines: [
          {
            role: "them",
            ja: "ごちゅうもんは？",
            romaji: "gochuumon wa?",
            meaning: bi("Your order?", "আপনার অর্ডার?"),
          },
          you("You want ramen and water.", "রামেন ও পানি চান।", [
            {
              ja: "ラーメンと みずを ください。",
              romaji: "raamen to mizu o kudasai",
              en: "Ramen and water, please.",
              bn: "রামেন ও পানি দিন।",
              correct: true,
            },
            {
              ja: "がっこうに いきます。",
              romaji: "gakkou ni ikimasu",
              en: "I go to school.",
              bn: "স্কুলে যাই।",
              correct: false,
            },
          ]),
        ],
      },
    ],
  ),

  lesson(
    "likes-and-weather",
    "living",
    U7,
    20,
    "like",
    bi("Likes and weather", "পছন্দ ও আবহাওয়া"),
    bi("Feelings about food, cats, and the sky.", "খাবার, বিড়াল ও আকাশ নিয়ে অনুভূতি।"),
    [
      scene("like", "A park. Wind. Someone smiles at a cat, then at the sky.", "পার্ক। হাওয়া। কেউ বিড়াল দেখে হাসে, তারপর আকাশে।"),
      hear("ねこが すきです。", "neko ga suki desu", "I like cats.", "আমি বিড়াল পছন্দ করি।"),
      hear("コーヒーが すきです。", "koohii ga suki desu", "I like coffee.", "আমি কফি পছন্দ করি।"),
      hear("スポーツが すきじゃありません。", "supootsu ga suki ja arimasen", "I don't like sports.", "আমি খেলাধুলা পছন্দ করি না।"),
      scene("weather", "The same park. Bright, then a grey sheet of cloud.", "একই পার্ক। উজ্জ্বল, তারপর ধূসর মেঘ।"),
      hear("きょうは いい てんきです。", "kyou wa ii tenki desu", "The weather is nice today.", "আজ আবহাওয়া ভালো।"),
      hear("あついです。", "atsui desu", "It's hot.", "গরম।"),
      hear("さむいです。", "samui desu", "It's cold.", "ঠান্ডা।"),
      hear("あめです。", "ame desu", "It's rain.", "বৃষ্টি।"),
      pattern(
        [
          ["すきです", "suki desu", "like", "পছন্দ"],
          ["すきじゃありません", "suki ja arimasen", "don't like", "পছন্দ নয়"],
          ["あついです", "atsui desu", "hot", "গরম"],
          ["さむいです", "samui desu", "cold", "ঠান্ডা"],
        ],
        "が in ねこが すきです marks what the feeling points at. じゃありません gently turns a statement around. You do not need a grammar page — you felt the no.",
        "ねこが すきです-এর が বলে অনুভূতি কার দিকে। じゃありません আলতো করে উল্টে দেয়। ব্যাকরণ পাতা নয় — 'না' অনুভব করেছেন।",
      ),
      useIt("You like tea.", "আপনি চা পছন্দ করেন।", [
        {
          ja: "おちゃが すきです。",
          romaji: "ocha ga suki desu",
          en: "I like tea.",
          bn: "চা পছন্দ করি।",
          correct: true,
        },
        {
          ja: "おちゃを ください。",
          romaji: "ocha o kudasai",
          en: "Tea, please. (ordering)",
          bn: "চা দিন। (অর্ডার)",
          correct: false,
        },
        { ja: "さむいです。", romaji: "samui desu", en: "It's cold.", bn: "ঠান্ডা।", correct: false },
      ]),
      kanjiMeet("あめ", "雨", "あめ", "今日は 雨です。", "kyou wa ame desu", "It's rain today.", "আজ বৃষ্টি।"),
      {
        kind: "talk",
        lines: [
          {
            role: "them",
            ja: "なにが すきですか。",
            romaji: "nani ga suki desu ka",
            meaning: bi("What do you like?", "কী পছন্দ করেন?"),
          },
          you("You like cats.", "বিড়াল পছন্দ করেন।", [
            {
              ja: "ねこが すきです。",
              romaji: "neko ga suki desu",
              en: "I like cats.",
              bn: "বিড়াল পছন্দ করি।",
              correct: true,
            },
            { ja: "ただいま。", romaji: "tadaima", en: "I'm home.", bn: "আমি এসেছি।", correct: false },
          ]),
        ],
      },
    ],
  ),
];
