/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConversationRouteImport } from './routes/conversation'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as HiraganaRouteImport } from './routes/hiragana'
import { Route as KanjiRouteImport } from './routes/kanji'
import { Route as KatakanaRouteImport } from './routes/katakana'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ListenRouteImport } from './routes/listen'
import { Route as MoreRouteImport } from './routes/more'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SpeakRouteImport } from './routes/speak'
import { Route as DialogueIdRouteImport } from './routes/dialogue.$id'
import { Route as LessonIdRouteImport } from './routes/lesson.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationRoute = ConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const HiraganaRoute = HiraganaRouteImport.update({
  id: '/hiragana',
  path: '/hiragana',
  getParentRoute: () => rootRouteImport,
} as any)
const KanjiRoute = KanjiRouteImport.update({
  id: '/kanji',
  path: '/kanji',
  getParentRoute: () => rootRouteImport,
} as any)
const KatakanaRoute = KatakanaRouteImport.update({
  id: '/katakana',
  path: '/katakana',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenRoute = ListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakRoute = SpeakRouteImport.update({
  id: '/speak',
  path: '/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogueIdRoute = DialogueIdRouteImport.update({
  id: '/dialogue/$id',
  path: '/dialogue/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonIdRoute = LessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversation': typeof ConversationRoute
  '/daily': typeof DailyRoute
  '/hiragana': typeof HiraganaRoute
  '/kanji': typeof KanjiRoute
  '/katakana': typeof KatakanaRoute
  '/learn': typeof LearnRoute
  '/listen': typeof ListenRoute
  '/more': typeof MoreRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/speak': typeof SpeakRoute
  '/dialogue/$id': typeof DialogueIdRoute
  '/lesson/$id': typeof LessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversation': typeof ConversationRoute
  '/daily': typeof DailyRoute
  '/hiragana': typeof HiraganaRoute
  '/kanji': typeof KanjiRoute
  '/katakana': typeof KatakanaRoute
  '/learn': typeof LearnRoute
  '/listen': typeof ListenRoute
  '/more': typeof MoreRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/speak': typeof SpeakRoute
  '/dialogue/$id': typeof DialogueIdRoute
  '/lesson/$id': typeof LessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversation': typeof ConversationRoute
  '/daily': typeof DailyRoute
  '/hiragana': typeof HiraganaRoute
  '/kanji': typeof KanjiRoute
  '/katakana': typeof KatakanaRoute
  '/learn': typeof LearnRoute
  '/listen': typeof ListenRoute
  '/more': typeof MoreRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/speak': typeof SpeakRoute
  '/dialogue/$id': typeof DialogueIdRoute
  '/lesson/$id': typeof LessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversation'
    | '/daily'
    | '/hiragana'
    | '/kanji'
    | '/katakana'
    | '/learn'
    | '/listen'
    | '/more'
    | '/progress'
    | '/review'
    | '/settings'
    | '/speak'
    | '/dialogue/$id'
    | '/lesson/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversation'
    | '/daily'
    | '/hiragana'
    | '/kanji'
    | '/katakana'
    | '/learn'
    | '/listen'
    | '/more'
    | '/progress'
    | '/review'
    | '/settings'
    | '/speak'
    | '/dialogue/$id'
    | '/lesson/$id'
  id:
    | '__root__'
    | '/'
    | '/conversation'
    | '/daily'
    | '/hiragana'
    | '/kanji'
    | '/katakana'
    | '/learn'
    | '/listen'
    | '/more'
    | '/progress'
    | '/review'
    | '/settings'
    | '/speak'
    | '/dialogue/$id'
    | '/lesson/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversationRoute: typeof ConversationRoute
  DailyRoute: typeof DailyRoute
  HiraganaRoute: typeof HiraganaRoute
  KanjiRoute: typeof KanjiRoute
  KatakanaRoute: typeof KatakanaRoute
  LearnRoute: typeof LearnRoute
  ListenRoute: typeof ListenRoute
  MoreRoute: typeof MoreRoute
  ProgressRoute: typeof ProgressRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  SpeakRoute: typeof SpeakRoute
  DialogueIdRoute: typeof DialogueIdRoute
  LessonIdRoute: typeof LessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation': {
      id: '/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof ConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiragana': {
      id: '/hiragana'
      path: '/hiragana'
      fullPath: '/hiragana'
      preLoaderRoute: typeof HiraganaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanji': {
      id: '/kanji'
      path: '/kanji'
      fullPath: '/kanji'
      preLoaderRoute: typeof KanjiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katakana': {
      id: '/katakana'
      path: '/katakana'
      fullPath: '/katakana'
      preLoaderRoute: typeof KatakanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen': {
      id: '/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof ListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speak': {
      id: '/speak'
      path: '/speak'
      fullPath: '/speak'
      preLoaderRoute: typeof SpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialogue/$id': {
      id: '/dialogue/$id'
      path: '/dialogue/$id'
      fullPath: '/dialogue/$id'
      preLoaderRoute: typeof DialogueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$id': {
      id: '/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof LessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversationRoute: ConversationRoute,
  DailyRoute: DailyRoute,
  HiraganaRoute: HiraganaRoute,
  KanjiRoute: KanjiRoute,
  KatakanaRoute: KatakanaRoute,
  LearnRoute: LearnRoute,
  ListenRoute: ListenRoute,
  MoreRoute: MoreRoute,
  ProgressRoute: ProgressRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  SpeakRoute: SpeakRoute,
  DialogueIdRoute: DialogueIdRoute,
  LessonIdRoute: LessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
